### ISSUE TITLE
Flow Launcher error JetBrainsIDEProjects

### ISSUE THREAD

**Issue by Pixefora** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#1]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 04/05/2023 13:45:00
Exception:
JetBrainsIDEProjects Exception: 
Websites: https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects
Author: kenty02
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: File not found: C:\Users\Jorge\AppData\Local\JetBrains\Toolbox\cache\intellij_projects.json. Is toolbox installed?
 ---> System.IO.FileNotFoundException: File not found: C:\Users\Jorge\AppData\Local\JetBrains\Toolbox\cache\intellij_projects.json. Is toolbox installed?
   at Flow.Launcher.Plugin.JetBrainsIDEProjects.ToolboxCacheReader.Read()
   at Flow.Launcher.Plugin.JetBrainsIDEProjects.JetBrainsIDEProjects.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2023-04-05.txt](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/files/11158289/2023-04-05.txt)

**Comment by kenty02** [comment]
I can't seem to reproduce this in my environment. Have you started the toolbox at least once after installing it? After that, it should generate `%LOCALAPPDATA%\JetBrains\Toolbox\cache\intellij_projects.json`.

**Comment by TriTamLe** [comment]
@kenty02 
I have run the Toolbox and it does not generate the file intellij_projects.json. I am using Webstorm so there is no Intelij in my computer and version of the Jetbrain Toolbox is _JetBrains Toolbox 2.2.1.19765, Windows 11, x64_
![image](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/assets/68864207/fd798047-5bca-4347-b9c5-2287e2ef0252)

**Comment by luthfisolahudin** [comment]
@TriTamLe I think newer Toolbox does not generate `intellij_project.json` anymore. I create [python script to generate that](https://github.com/luthfisolahudin/toolbox-cache-generator), maybe you could try.

**Comment by kenty02** [comment]
@TriTamLe @luthfisolahudin Thanks, I've released v3.0.0 for the latest toolbox based on @luthfisolahudin's python script, give it a try. It will be available in the plugin store in a few hours or so.

**Comment by TriTamLe** [comment]
@kenty02  @luthfisolahudin  it works! ╰(*°▽°*)╯Thank you guys

**Comment by luthfisolahudin** [comment]
@kenty02 Thank you for your awesome plugin!
