### ISSUE TITLE
Error when using the plugin

### ISSUE THREAD

**Issue by BLACK4585** [kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects#9]
I get this error when using the `jb` keyword, so using this plugin.
Error:

```
Flow Launcher version: 1.16.1
OS Version: 22621.2134
IntPtr Length: 8
x64: True

Python Path: C:\Users\jonan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 08/27/2023 00:02:23
Exception:
JetBrainsIDEProjects Exception: 
Websites: https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects
Author: kenty02
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Failed to determine application icon file.
 ---> System.IO.FileNotFoundException: Failed to determine application icon file.
   at Flow.Launcher.Plugin.JetBrainsIDEProjects.ToolboxCacheReader.GetApplications()
   at Flow.Launcher.Plugin.JetBrainsIDEProjects.JetBrainsIDEProjects.Query(Query query)
   at System.Threading.Tasks.Task\`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func\`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[2023-08-27.txt](https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects/files/12446805/2023-08-27.txt)

**Comment by matheusgarcez** [comment]
The id "ReSharper-U" is missing from the blacklist.

**Comment by BLACK4585** [comment]
What does this mean?
